baseurl = "http://www.leolampo.gq" 
title = "LeoLampo" 
theme = "coder-portfolio"
languagecode = "en"
defaultcontentlanguage = "en" 

paginate = 20 # Default number of pages per page in pagination.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.
pygmentsUseClasses = true # new add

disqusShortname = "yourdiscussshortname" # Enable or disable Disqus.

[params] # theme parameters
    author = "LeoLampo" # Author's name.
    info = "La merce arriva in un lampo!" # Author's job title or info.
    description = "leolampo" # Site description.
    keywords = "lampo,leolampo,ilsilenzio" # Site keywords.
    avatarurl = "images/avatar.jpg" # Contain the path of the optionnal avatar in the static folder.
	
    # Whether you want to hide copyright and credits in the footer.
    hideCredits = false
    hideCopyright = false

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.

# Social links
[[params.social]]
    name = "dev site"
    icon = "fab fa-github"
    weight = 1
    url = "https://thedoofmodern.gq"


# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "posts"
[[menu.main]]
    name = "About"
    weight = 2
    url = "about"
